# List of EU countries
countries <- c("Austria",
               "Belgium",
               "Bulgaria",
               "Croatia",
               "Cyprus",
               "Czechia",
               "Denmark",
               "Estonia",
               "Finland",
               "France",
               "Germany",
               "Greece",
               "Hungary",
               "Ireland",
               "Italy",
               "Latvia",
               "Lithuania",
               "Luxembourg",
               "Malta",
               "Netherlands",
               "Poland",
               "Portugal",
               "Romania",
               "Slovakia",
               "Slovenia",
               "Spain",
               "Sweden")

industries <- c("Insurance",
                "Restaurant",
                "Autommotive")
